language: java
jdk:
  - oraclejdk8
  - oraclejdk7
script:
 - mvn verify
after_success:
 - mvn clean install -Dmaven.test.skip=true
after_failure:
notifications:
  email:
    - rmartinramos@soldevelo.com